branch-defaults:
  default:
    environment: Storefront2-env
environment-defaults:
  Storefront2-env:
    branch: null
    repository: null
global:
  application_name: StoreFront2
  default_ec2_keyname: null
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: default
  sc: null
  workspace_type: Application
# deploy:
#   artifact: dist/Archive.zip 
