version: 2.1
# orgs contain basc recipes and reproducible actions (install node, aws, etc.)
orbs:
  node: circleci/node@5.0.3
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.4

jobs:
  build_back_and_testing_it:
    docker:
      - image: "cimg/base:stable"
      - image: "circleci/postgres:12-alpine-ram"
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: toor
          POSTGRES_DB: store_test
    steps:
      - node/install:
          node-version: '16.18'
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "./back/package.json" }}
            - v1-npm-deps-
      - run:
          name : "install node modules"
          command: npm run back:install
      - save_cache:
          key: v1-npm-deps-{{ checksum "./back/package.json" }}
          paths:
            - .back/node_modules
      - run:
          name: "bulding back dist"
          command : npm run back:build
      - run:
          name : "initialize db"
          command : npm run db:init
      - run:
          name: "testing app"
          command : npm run back:test    
  build_front:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install:
          node-version: '18.12'
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "./front/package.json" }}
            - v1-npm-deps-
      - run:
          name : "install node modules"
          command: npm run front:install

      - save_cache:
          key: v1-npm-deps-{{ checksum "./front/package.json" }}
          paths:
            - .front/node_modules
      - run:
          name: "bulding front dist"
          command : npm run front:build
  deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install:
          node-version: '18.12'
      - aws-cli/setup
      - eb/setup
      - checkout
      # buliding back 
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "./back/package.json" }}
            - v1-npm-deps-
      - run:
          name : "install node modules"
          command: npm run back:install
      - save_cache:
          key: v1-npm-deps-{{ checksum "./back/package.json" }}
          paths:
            - .back/node_modules
      - run:
          name: "bulding back dist"
          command : npm run back:build
      # building front
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "./front/package.json" }}
            - v1-npm-deps-
      - run:
          name : "install node modules"
          command: npm run front:install

      - save_cache:
          key: v1-npm-deps-{{ checksum "./front/package.json" }}
          paths:
            - .front/node_modules
      - run:
          name: "bulding front dist"
          command : npm run front:build
workflows:
  project_3:
    jobs:
      - build_back_and_testing_it
      - build_front
      - hold:
          filters:
            branches:
              only:
                - master
          type: approval
          requires:
            - build_back_and_testing_it
            - build_front
      # - deploy:
      #     requires: hold